#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBIC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TBCI Server")]
	public partial class TBICDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDEPARTMENT(DEPARTMENT instance);
    partial void UpdateDEPARTMENT(DEPARTMENT instance);
    partial void DeleteDEPARTMENT(DEPARTMENT instance);
    partial void InsertPRODUCT(PRODUCT instance);
    partial void UpdatePRODUCT(PRODUCT instance);
    partial void DeletePRODUCT(PRODUCT instance);
    partial void InsertSALE_DETAIL(SALE_DETAIL instance);
    partial void UpdateSALE_DETAIL(SALE_DETAIL instance);
    partial void DeleteSALE_DETAIL(SALE_DETAIL instance);
    partial void InsertSALE(SALE instance);
    partial void UpdateSALE(SALE instance);
    partial void DeleteSALE(SALE instance);
    partial void InsertSTAFFINFO(STAFFINFO instance);
    partial void UpdateSTAFFINFO(STAFFINFO instance);
    partial void DeleteSTAFFINFO(STAFFINFO instance);
    #endregion
		
		public TBICDataContext() : 
				base(global::TBIC.Properties.Settings.Default.TBCI_ServerConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public TBICDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TBICDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TBICDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TBICDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DEPARTMENT> DEPARTMENTs
		{
			get
			{
				return this.GetTable<DEPARTMENT>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCT> PRODUCTs
		{
			get
			{
				return this.GetTable<PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<SALE_DETAIL> SALE_DETAILs
		{
			get
			{
				return this.GetTable<SALE_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<SALE> SALEs
		{
			get
			{
				return this.GetTable<SALE>();
			}
		}
		
		public System.Data.Linq.Table<STAFF> STAFFs
		{
			get
			{
				return this.GetTable<STAFF>();
			}
		}
		
		public System.Data.Linq.Table<STAFFINFO> STAFFINFOs
		{
			get
			{
				return this.GetTable<STAFFINFO>();
			}
		}
		
		public System.Data.Linq.Table<vw_Retrieve> vw_Retrieves
		{
			get
			{
				return this.GetTable<vw_Retrieve>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ADD_STAFF")]
		public int ADD_STAFF([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAFF_NAME", DbType="NVarChar(100)")] string sTAFF_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(100)")] string pASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTAFF_NAME, uSERNAME, pASSWORD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ADD_STOCK")]
		public int ADD_STOCK([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRODUCT_ID", DbType="Int")] System.Nullable<int> pRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QUANTITY", DbType="Int")] System.Nullable<int> qUANTITY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRODUCT_ID, qUANTITY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DEDUCT_STOCK")]
		public int DEDUCT_STOCK([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRODUCT_ID", DbType="Int")] System.Nullable<int> pRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QUANTITY", DbType="Int")] System.Nullable<int> qUANTITY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRODUCT_ID, qUANTITY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DELETE_STAFF")]
		public int DELETE_STAFF([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAFF_ID", DbType="Int")] System.Nullable<int> sTAFF_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTAFF_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EDIT_STAFF")]
		public int EDIT_STAFF([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAFF_ID", DbType="Int")] System.Nullable<int> sTAFF_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAFF_NAME", DbType="NVarChar(100)")] string sTAFF_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="NVarChar(100)")] string pASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTAFF_ID, sTAFF_NAME, uSERNAME, pASSWORD);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPARTMENT")]
	public partial class DEPARTMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DEPARTMENT_ID;
		
		private string _DEPARTMENT_NAME;
		
		private EntitySet<STAFFINFO> _STAFFINFOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEPARTMENT_IDChanging(int value);
    partial void OnDEPARTMENT_IDChanged();
    partial void OnDEPARTMENT_NAMEChanging(string value);
    partial void OnDEPARTMENT_NAMEChanged();
    #endregion
		
		public DEPARTMENT()
		{
			this._STAFFINFOs = new EntitySet<STAFFINFO>(new Action<STAFFINFO>(this.attach_STAFFINFOs), new Action<STAFFINFO>(this.detach_STAFFINFOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DEPARTMENT_ID
		{
			get
			{
				return this._DEPARTMENT_ID;
			}
			set
			{
				if ((this._DEPARTMENT_ID != value))
				{
					this.OnDEPARTMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._DEPARTMENT_ID = value;
					this.SendPropertyChanged("DEPARTMENT_ID");
					this.OnDEPARTMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT_NAME", DbType="NVarChar(100)")]
		public string DEPARTMENT_NAME
		{
			get
			{
				return this._DEPARTMENT_NAME;
			}
			set
			{
				if ((this._DEPARTMENT_NAME != value))
				{
					this.OnDEPARTMENT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DEPARTMENT_NAME = value;
					this.SendPropertyChanged("DEPARTMENT_NAME");
					this.OnDEPARTMENT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTMENT_STAFFINFO", Storage="_STAFFINFOs", ThisKey="DEPARTMENT_ID", OtherKey="DEPARTMENT_ID")]
		public EntitySet<STAFFINFO> STAFFINFOs
		{
			get
			{
				return this._STAFFINFOs;
			}
			set
			{
				this._STAFFINFOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_STAFFINFOs(STAFFINFO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTMENT = this;
		}
		
		private void detach_STAFFINFOs(STAFFINFO entity)
		{
			this.SendPropertyChanging();
			entity.DEPARTMENT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTS")]
	public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PRODUCT_ID;
		
		private string _PRODUCT_NAME;
		
		private string _FLAVOR;
		
		private System.Nullable<decimal> _PRICE;
		
		private string _STATUS;
		
		private EntitySet<SALE_DETAIL> _SALE_DETAILs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRODUCT_IDChanging(int value);
    partial void OnPRODUCT_IDChanged();
    partial void OnPRODUCT_NAMEChanging(string value);
    partial void OnPRODUCT_NAMEChanged();
    partial void OnFLAVORChanging(string value);
    partial void OnFLAVORChanged();
    partial void OnPRICEChanging(System.Nullable<decimal> value);
    partial void OnPRICEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    #endregion
		
		public PRODUCT()
		{
			this._SALE_DETAILs = new EntitySet<SALE_DETAIL>(new Action<SALE_DETAIL>(this.attach_SALE_DETAILs), new Action<SALE_DETAIL>(this.detach_SALE_DETAILs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PRODUCT_ID
		{
			get
			{
				return this._PRODUCT_ID;
			}
			set
			{
				if ((this._PRODUCT_ID != value))
				{
					this.OnPRODUCT_IDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_ID = value;
					this.SendPropertyChanged("PRODUCT_ID");
					this.OnPRODUCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_NAME", DbType="NVarChar(100)")]
		public string PRODUCT_NAME
		{
			get
			{
				return this._PRODUCT_NAME;
			}
			set
			{
				if ((this._PRODUCT_NAME != value))
				{
					this.OnPRODUCT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_NAME = value;
					this.SendPropertyChanged("PRODUCT_NAME");
					this.OnPRODUCT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAVOR", DbType="NVarChar(50)")]
		public string FLAVOR
		{
			get
			{
				return this._FLAVOR;
			}
			set
			{
				if ((this._FLAVOR != value))
				{
					this.OnFLAVORChanging(value);
					this.SendPropertyChanging();
					this._FLAVOR = value;
					this.SendPropertyChanged("FLAVOR");
					this.OnFLAVORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_SALE_DETAIL", Storage="_SALE_DETAILs", ThisKey="PRODUCT_ID", OtherKey="PRODUCT_ID")]
		public EntitySet<SALE_DETAIL> SALE_DETAILs
		{
			get
			{
				return this._SALE_DETAILs;
			}
			set
			{
				this._SALE_DETAILs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SALE_DETAILs(SALE_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT = this;
		}
		
		private void detach_SALE_DETAILs(SALE_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALE_DETAILS")]
	public partial class SALE_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SALE_DETAIL_ID;
		
		private int _SALE_ID;
		
		private int _PRODUCT_ID;
		
		private int _QUANTITY;
		
		private decimal _UNIT_PRICE;
		
		private decimal _SUBTOTAL;
		
		private EntityRef<PRODUCT> _PRODUCT;
		
		private EntityRef<SALE> _SALE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSALE_DETAIL_IDChanging(int value);
    partial void OnSALE_DETAIL_IDChanged();
    partial void OnSALE_IDChanging(int value);
    partial void OnSALE_IDChanged();
    partial void OnPRODUCT_IDChanging(int value);
    partial void OnPRODUCT_IDChanged();
    partial void OnQUANTITYChanging(int value);
    partial void OnQUANTITYChanged();
    partial void OnUNIT_PRICEChanging(decimal value);
    partial void OnUNIT_PRICEChanged();
    partial void OnSUBTOTALChanging(decimal value);
    partial void OnSUBTOTALChanged();
    #endregion
		
		public SALE_DETAIL()
		{
			this._PRODUCT = default(EntityRef<PRODUCT>);
			this._SALE = default(EntityRef<SALE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_DETAIL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SALE_DETAIL_ID
		{
			get
			{
				return this._SALE_DETAIL_ID;
			}
			set
			{
				if ((this._SALE_DETAIL_ID != value))
				{
					this.OnSALE_DETAIL_IDChanging(value);
					this.SendPropertyChanging();
					this._SALE_DETAIL_ID = value;
					this.SendPropertyChanged("SALE_DETAIL_ID");
					this.OnSALE_DETAIL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_ID", DbType="Int NOT NULL")]
		public int SALE_ID
		{
			get
			{
				return this._SALE_ID;
			}
			set
			{
				if ((this._SALE_ID != value))
				{
					if (this._SALE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSALE_IDChanging(value);
					this.SendPropertyChanging();
					this._SALE_ID = value;
					this.SendPropertyChanged("SALE_ID");
					this.OnSALE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ID", DbType="Int NOT NULL")]
		public int PRODUCT_ID
		{
			get
			{
				return this._PRODUCT_ID;
			}
			set
			{
				if ((this._PRODUCT_ID != value))
				{
					if (this._PRODUCT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPRODUCT_IDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_ID = value;
					this.SendPropertyChanged("PRODUCT_ID");
					this.OnPRODUCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_PRICE", DbType="Decimal(10,2) NOT NULL")]
		public decimal UNIT_PRICE
		{
			get
			{
				return this._UNIT_PRICE;
			}
			set
			{
				if ((this._UNIT_PRICE != value))
				{
					this.OnUNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._UNIT_PRICE = value;
					this.SendPropertyChanged("UNIT_PRICE");
					this.OnUNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTOTAL", DbType="Decimal(10,2) NOT NULL")]
		public decimal SUBTOTAL
		{
			get
			{
				return this._SUBTOTAL;
			}
			set
			{
				if ((this._SUBTOTAL != value))
				{
					this.OnSUBTOTALChanging(value);
					this.SendPropertyChanging();
					this._SUBTOTAL = value;
					this.SendPropertyChanged("SUBTOTAL");
					this.OnSUBTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_SALE_DETAIL", Storage="_PRODUCT", ThisKey="PRODUCT_ID", OtherKey="PRODUCT_ID", IsForeignKey=true)]
		public PRODUCT PRODUCT
		{
			get
			{
				return this._PRODUCT.Entity;
			}
			set
			{
				PRODUCT previousValue = this._PRODUCT.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCT.Entity = null;
						previousValue.SALE_DETAILs.Remove(this);
					}
					this._PRODUCT.Entity = value;
					if ((value != null))
					{
						value.SALE_DETAILs.Add(this);
						this._PRODUCT_ID = value.PRODUCT_ID;
					}
					else
					{
						this._PRODUCT_ID = default(int);
					}
					this.SendPropertyChanged("PRODUCT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALE_SALE_DETAIL", Storage="_SALE", ThisKey="SALE_ID", OtherKey="SALES_ID", IsForeignKey=true)]
		public SALE SALE
		{
			get
			{
				return this._SALE.Entity;
			}
			set
			{
				SALE previousValue = this._SALE.Entity;
				if (((previousValue != value) 
							|| (this._SALE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SALE.Entity = null;
						previousValue.SALE_DETAILs.Remove(this);
					}
					this._SALE.Entity = value;
					if ((value != null))
					{
						value.SALE_DETAILs.Add(this);
						this._SALE_ID = value.SALES_ID;
					}
					else
					{
						this._SALE_ID = default(int);
					}
					this.SendPropertyChanged("SALE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALES")]
	public partial class SALE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SALES_ID;
		
		private int _STAFF_ID;
		
		private System.DateTime _SALES_DATE;
		
		private decimal _TOTAL_AMOUNT;
		
		private string _PAYMENT_METHOD;
		
		private decimal _AMOUNT_PAID;
		
		private decimal _CHANGE_AMOUNT;
		
		private EntitySet<SALE_DETAIL> _SALE_DETAILs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSALES_IDChanging(int value);
    partial void OnSALES_IDChanged();
    partial void OnSTAFF_IDChanging(int value);
    partial void OnSTAFF_IDChanged();
    partial void OnSALES_DATEChanging(System.DateTime value);
    partial void OnSALES_DATEChanged();
    partial void OnTOTAL_AMOUNTChanging(decimal value);
    partial void OnTOTAL_AMOUNTChanged();
    partial void OnPAYMENT_METHODChanging(string value);
    partial void OnPAYMENT_METHODChanged();
    partial void OnAMOUNT_PAIDChanging(decimal value);
    partial void OnAMOUNT_PAIDChanged();
    partial void OnCHANGE_AMOUNTChanging(decimal value);
    partial void OnCHANGE_AMOUNTChanged();
    #endregion
		
		public SALE()
		{
			this._SALE_DETAILs = new EntitySet<SALE_DETAIL>(new Action<SALE_DETAIL>(this.attach_SALE_DETAILs), new Action<SALE_DETAIL>(this.detach_SALE_DETAILs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALES_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SALES_ID
		{
			get
			{
				return this._SALES_ID;
			}
			set
			{
				if ((this._SALES_ID != value))
				{
					this.OnSALES_IDChanging(value);
					this.SendPropertyChanging();
					this._SALES_ID = value;
					this.SendPropertyChanged("SALES_ID");
					this.OnSALES_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_ID", DbType="Int NOT NULL")]
		public int STAFF_ID
		{
			get
			{
				return this._STAFF_ID;
			}
			set
			{
				if ((this._STAFF_ID != value))
				{
					this.OnSTAFF_IDChanging(value);
					this.SendPropertyChanging();
					this._STAFF_ID = value;
					this.SendPropertyChanged("STAFF_ID");
					this.OnSTAFF_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALES_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime SALES_DATE
		{
			get
			{
				return this._SALES_DATE;
			}
			set
			{
				if ((this._SALES_DATE != value))
				{
					this.OnSALES_DATEChanging(value);
					this.SendPropertyChanging();
					this._SALES_DATE = value;
					this.SendPropertyChanged("SALES_DATE");
					this.OnSALES_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Decimal(10,2) NOT NULL")]
		public decimal TOTAL_AMOUNT
		{
			get
			{
				return this._TOTAL_AMOUNT;
			}
			set
			{
				if ((this._TOTAL_AMOUNT != value))
				{
					this.OnTOTAL_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_AMOUNT = value;
					this.SendPropertyChanged("TOTAL_AMOUNT");
					this.OnTOTAL_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_METHOD", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string PAYMENT_METHOD
		{
			get
			{
				return this._PAYMENT_METHOD;
			}
			set
			{
				if ((this._PAYMENT_METHOD != value))
				{
					this.OnPAYMENT_METHODChanging(value);
					this.SendPropertyChanging();
					this._PAYMENT_METHOD = value;
					this.SendPropertyChanged("PAYMENT_METHOD");
					this.OnPAYMENT_METHODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT_PAID", DbType="Decimal(10,2) NOT NULL")]
		public decimal AMOUNT_PAID
		{
			get
			{
				return this._AMOUNT_PAID;
			}
			set
			{
				if ((this._AMOUNT_PAID != value))
				{
					this.OnAMOUNT_PAIDChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT_PAID = value;
					this.SendPropertyChanged("AMOUNT_PAID");
					this.OnAMOUNT_PAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_AMOUNT", DbType="Decimal(10,2) NOT NULL")]
		public decimal CHANGE_AMOUNT
		{
			get
			{
				return this._CHANGE_AMOUNT;
			}
			set
			{
				if ((this._CHANGE_AMOUNT != value))
				{
					this.OnCHANGE_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._CHANGE_AMOUNT = value;
					this.SendPropertyChanged("CHANGE_AMOUNT");
					this.OnCHANGE_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALE_SALE_DETAIL", Storage="_SALE_DETAILs", ThisKey="SALES_ID", OtherKey="SALE_ID")]
		public EntitySet<SALE_DETAIL> SALE_DETAILs
		{
			get
			{
				return this._SALE_DETAILs;
			}
			set
			{
				this._SALE_DETAILs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SALE_DETAILs(SALE_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.SALE = this;
		}
		
		private void detach_SALE_DETAILs(SALE_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.SALE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STAFF")]
	public partial class STAFF
	{
		
		private int _STAFF_ID;
		
		private string _STAFF_NAME;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		public STAFF()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_ID", DbType="Int NOT NULL")]
		public int STAFF_ID
		{
			get
			{
				return this._STAFF_ID;
			}
			set
			{
				if ((this._STAFF_ID != value))
				{
					this._STAFF_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STAFF_NAME
		{
			get
			{
				return this._STAFF_NAME;
			}
			set
			{
				if ((this._STAFF_NAME != value))
				{
					this._STAFF_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STAFFINFO")]
	public partial class STAFFINFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAFF_ID;
		
		private string _STAFF_NAME;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private System.Nullable<int> _DEPARTMENT_ID;
		
		private string _ROLE;
		
		private EntityRef<DEPARTMENT> _DEPARTMENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAFF_IDChanging(int value);
    partial void OnSTAFF_IDChanged();
    partial void OnSTAFF_NAMEChanging(string value);
    partial void OnSTAFF_NAMEChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnDEPARTMENT_IDChanging(System.Nullable<int> value);
    partial void OnDEPARTMENT_IDChanged();
    partial void OnROLEChanging(string value);
    partial void OnROLEChanged();
    #endregion
		
		public STAFFINFO()
		{
			this._DEPARTMENT = default(EntityRef<DEPARTMENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAFF_ID
		{
			get
			{
				return this._STAFF_ID;
			}
			set
			{
				if ((this._STAFF_ID != value))
				{
					this.OnSTAFF_IDChanging(value);
					this.SendPropertyChanging();
					this._STAFF_ID = value;
					this.SendPropertyChanged("STAFF_ID");
					this.OnSTAFF_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_NAME", DbType="NVarChar(100)")]
		public string STAFF_NAME
		{
			get
			{
				return this._STAFF_NAME;
			}
			set
			{
				if ((this._STAFF_NAME != value))
				{
					this.OnSTAFF_NAMEChanging(value);
					this.SendPropertyChanging();
					this._STAFF_NAME = value;
					this.SendPropertyChanged("STAFF_NAME");
					this.OnSTAFF_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(100)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT_ID", DbType="Int")]
		public System.Nullable<int> DEPARTMENT_ID
		{
			get
			{
				return this._DEPARTMENT_ID;
			}
			set
			{
				if ((this._DEPARTMENT_ID != value))
				{
					if (this._DEPARTMENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEPARTMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._DEPARTMENT_ID = value;
					this.SendPropertyChanged("DEPARTMENT_ID");
					this.OnDEPARTMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="NVarChar(100)")]
		public string ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this.OnROLEChanging(value);
					this.SendPropertyChanging();
					this._ROLE = value;
					this.SendPropertyChanged("ROLE");
					this.OnROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DEPARTMENT_STAFFINFO", Storage="_DEPARTMENT", ThisKey="DEPARTMENT_ID", OtherKey="DEPARTMENT_ID", IsForeignKey=true)]
		public DEPARTMENT DEPARTMENT
		{
			get
			{
				return this._DEPARTMENT.Entity;
			}
			set
			{
				DEPARTMENT previousValue = this._DEPARTMENT.Entity;
				if (((previousValue != value) 
							|| (this._DEPARTMENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DEPARTMENT.Entity = null;
						previousValue.STAFFINFOs.Remove(this);
					}
					this._DEPARTMENT.Entity = value;
					if ((value != null))
					{
						value.STAFFINFOs.Add(this);
						this._DEPARTMENT_ID = value.DEPARTMENT_ID;
					}
					else
					{
						this._DEPARTMENT_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("DEPARTMENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Retrieve")]
	public partial class vw_Retrieve
	{
		
		private int _STAFF_ID;
		
		private string _STAFF_NAME;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _ROLE;
		
		private string _DEPARTMENT_NAME;
		
		public vw_Retrieve()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_ID", DbType="Int NOT NULL")]
		public int STAFF_ID
		{
			get
			{
				return this._STAFF_ID;
			}
			set
			{
				if ((this._STAFF_ID != value))
				{
					this._STAFF_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_NAME", DbType="NVarChar(100)")]
		public string STAFF_NAME
		{
			get
			{
				return this._STAFF_NAME;
			}
			set
			{
				if ((this._STAFF_NAME != value))
				{
					this._STAFF_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(100)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="NVarChar(100)")]
		public string ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this._ROLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT_NAME", DbType="NVarChar(100)")]
		public string DEPARTMENT_NAME
		{
			get
			{
				return this._DEPARTMENT_NAME;
			}
			set
			{
				if ((this._DEPARTMENT_NAME != value))
				{
					this._DEPARTMENT_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
