<?xml version="1.0" encoding="utf-8"?><Database Name="TBCI Server" Class="TBICDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NEKOARJZ\SQLEXPRESS;Initial Catalog=&quot;TBCI Server&quot;;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="TBIC.Properties.Settings" SettingsPropertyName="TBCI_ServerConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DEPARTMENT" Member="DEPARTMENTs">
    <Type Name="DEPARTMENT">
      <Column Name="DEPARTMENT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DEPARTMENT_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="DEPARTMENT_STAFF" Member="STAFFs" ThisKey="DEPARTMENT_ID" OtherKey="DEPARTMENT_ID" Type="STAFF" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PRODUCT_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FLAVOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STOCK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PRODUCT_SALE_DETAIL" Member="SALE_DETAILs" ThisKey="PRODUCT_ID" OtherKey="PRODUCT_ID" Type="SALE_DETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.SALE" Member="SALEs">
    <Type Name="SALE">
      <Column Name="SALES_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STAFF_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SALES_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNT" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="PAYMENT_METHOD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AMOUNT_PAID" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="CHANGE_AMOUNT" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="SALE_SALE_DETAIL" Member="SALE_DETAILs" ThisKey="SALES_ID" OtherKey="SALE_ID" Type="SALE_DETAIL" />
      <Association Name="STAFF_SALE" Member="STAFF" ThisKey="STAFF_ID" OtherKey="STAFF_ID" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SALE_DETAIL" Member="SALE_DETAILs">
    <Type Name="SALE_DETAIL">
      <Column Name="SALE_DETAIL_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SALE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIT_PRICE" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="SUBTOTAL" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="PRODUCT_SALE_DETAIL" Member="PRODUCT" ThisKey="PRODUCT_ID" OtherKey="PRODUCT_ID" Type="PRODUCT" IsForeignKey="true" />
      <Association Name="SALE_SALE_DETAIL" Member="SALE" ThisKey="SALE_ID" OtherKey="SALES_ID" Type="SALE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STAFF" Member="STAFFs">
    <Type Name="STAFF">
      <Column Name="STAFF_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEPARTMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="STAFF_SALE" Member="SALEs" ThisKey="STAFF_ID" OtherKey="STAFF_ID" Type="SALE" />
      <Association Name="DEPARTMENT_STAFF" Member="DEPARTMENT" ThisKey="DEPARTMENT_ID" OtherKey="DEPARTMENT_ID" Type="DEPARTMENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Retrieve" Member="vw_Retrieves">
    <Type Name="vw_Retrieve">
      <Column Name="STAFF_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ROLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEPARTMENT_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ADD_STAFF" Method="ADD_STAFF">
    <Parameter Name="STAFF_NAME" Parameter="sTAFF_NAME" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DEPARTMENT_ID" Parameter="dEPARTMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ROLE" Parameter="rOLE" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ADD_STOCK" Method="ADD_STOCK">
    <Parameter Name="PRODUCT_ID" Parameter="pRODUCT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QUANTITY" Parameter="qUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DEDUCT_STOCK" Method="DEDUCT_STOCK">
    <Parameter Name="PRODUCT_ID" Parameter="pRODUCT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QUANTITY" Parameter="qUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DELETE_STAFF" Method="DELETE_STAFF">
    <Parameter Name="STAFF_ID" Parameter="sTAFF_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EDIT_STAFF" Method="EDIT_STAFF">
    <Parameter Name="STAFF_ID" Parameter="sTAFF_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="STAFF_NAME" Parameter="sTAFF_NAME" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>